AWSTemplateFormatVersion: '2010-09-09'
Description: シンプルなVPCを作成するテンプレート

Resources:
  MyTestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Test-VPC
